# Generated by Django 3.2.8 on 2021-11-07 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('plant_growth', models.CharField(blank=True, max_length=255)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_organs',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('organs_name', models.CharField(max_length=50)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('is_disease', models.BooleanField()),
                ('harm_part', models.CharField(max_length=255)),
                ('cure', models.CharField(blank=True, max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('character', models.CharField(blank=True, max_length=255)),
                ('regularity', models.CharField(max_length=255)),
                ('measures', models.CharField(max_length=255)),
                ('photos', models.FileField(upload_to='resources/')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('harm_organs', models.ManyToManyField(to='searchSystem.Plant_organs')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchSystem.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
