# Generated by Django 3.2.8 on 2021-11-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchSystem', '0002_auto_20211112_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_disease',
            name='photos',
        ),
        migrations.AddField(
            model_name='plant_disease',
            name='photos_content',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='plant_disease',
            name='photos_main',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_growth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='update_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='character',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='cure',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='desc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='harm_part',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='measures',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='regularity',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='plant_disease',
            name='update_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_organs',
            name='update_time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
